# Generated by Django 4.0.4 on 2022-04-25 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonneAffiliee',
            fields=[
                ('id_personne_affiliee', models.AutoField(primary_key=True, serialize=False)),
                ('type_personne_affiliee', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'personne_affiliee',
            },
        ),
        migrations.CreateModel(
            name='PersonneVulnerable',
            fields=[
                ('id_personne_vulnerable', models.AutoField(primary_key=True, serialize=False)),
                ('nom_personne_vulnerable', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom_personne_vulnerable', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=16, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('temperature_normale', models.CharField(blank=True, max_length=30, null=True)),
                ('images_personne_vulnerable', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personne_vulnerable',
            },
        ),
        migrations.CreateModel(
            name='TypeAntecedentMedical',
            fields=[
                ('id_type_antecedent_medical', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'type_antecedent_medical',
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id_robot', models.AutoField(primary_key=True, serialize=False)),
                ('nom_robot', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse_ip', models.CharField(max_length=30, null=True)),
                ('id_personne_vulnerable', models.ForeignKey(blank=True, db_column='id_personne_vulnerable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.personnevulnerable')),
            ],
            options={
                'db_table': 'robot',
            },
        ),
        migrations.CreateModel(
            name='PersonneaffilieRobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps', models.DateTimeField(blank=True, null=True)),
                ('id_personne_affiliee', models.ForeignKey(blank=True, db_column='id_personne_affiliee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.personneaffiliee')),
                ('id_robot', models.ForeignKey(blank=True, db_column='id_robot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.robot')),
            ],
            options={
                'db_table': 'PersonneAffilie_Robot',
            },
        ),
        migrations.CreateModel(
            name='EnregistrementVideo',
            fields=[
                ('id_enregistrement_video', models.AutoField(primary_key=True, serialize=False)),
                ('heure_debut', models.DateTimeField(blank=True, null=True)),
                ('heure_fin', models.DateTimeField(blank=True, null=True)),
                ('data_enregistrement', models.DateField(blank=True, null=True)),
                ('piece', models.CharField(blank=True, max_length=40, null=True)),
                ('id_personne_affiliee', models.ForeignKey(blank=True, db_column='id_personne_affiliee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.personneaffiliee')),
            ],
            options={
                'db_table': 'enregistrement_video',
            },
        ),
        migrations.CreateModel(
            name='Constantes',
            fields=[
                ('id_constantes', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.CharField(blank=True, max_length=30, null=True)),
                ('tension', models.CharField(blank=True, max_length=30, null=True)),
                ('temps_de_prise', models.DateTimeField(blank=True, null=True)),
                ('id_personne_vulnerable', models.ForeignKey(blank=True, db_column='id_personne_vulnerable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.personnevulnerable')),
            ],
            options={
                'db_table': 'constantes',
            },
        ),
        migrations.CreateModel(
            name='AntecedentMedical',
            fields=[
                ('id_antecedent_medical', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_antecedent_medical', models.CharField(blank=True, max_length=50, null=True)),
                ('id_personne_vulnerable', models.ForeignKey(blank=True, db_column='id_personne_vulnerable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.personnevulnerable')),
                ('id_type_antecedent_medical', models.ForeignKey(blank=True, db_column='id_type_antecedent_medical', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.typeantecedentmedical')),
            ],
            options={
                'db_table': 'antecedent_medical',
            },
        ),
    ]
